name: Paper_Plugin
version: '1.0-SNAPSHOT'
main: io.github.codingmastermanager.paper_plugin.PaperPlugin
api-version: '1.21'
permissions:
  paperplugin.mods:
    description: "Mods, part of the Staff team"