name: Paper_Plugin
version: '1.0-SNAPSHOT'
main: io.github.codingmastermanager.paperPlugin.PaperPlugin
api-version: '1.21'
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true